export const Questions = [
  {
    prompt: "Which of the following is the correct name of React.js?",
    optionA: "React",
    optionB: "React.js",
    optionC: "ReactJS",
    optionD: "All of the above",
    asnwer: "optionD",
  },
  {
    prompt: "Which of the following command is used to install create-react-app?",
    optionA: "npm install -g create-react-app",
    optionB: "npm install create-react-app",
    optionC: "npm install -f create-react-app",
    optionD: "install -g create-react-app",
    asnwer: "optionA",
  },
  {
    prompt: "What of the following is used in React.js to increase performance?",
    optionA: "Original DOM",
    optionB: "Virtual DOM",
    optionC: "Both A and B.",
    optionD: "None of the above.",
    asnwer: "optionB",
  },
  {
    prompt: "Which of the following keyword is used to create a class inheritance?",
    optionA: "Create",
    optionB: "Inherits",
    optionC: "Extends",
    optionD: "This",
    asnwer: "optionC",
  },
  {
    prompt: "What are the two ways to handle data in React?",
    optionA: "State & Props",
    optionB: "Services & Components",
    optionC: "State & Services",
    optionD: "State & Component",
    asnwer: "optionA",
  },
  {
    prompt: "What is the default port where webpack-server runs?",
    optionA: "3000",
    optionB: "8080",
    optionC: "3030",
    optionD: "6060",
    asnwer: "optionB",
  },
  {
    prompt: "Which of the following option is correct in the case of the Babel?",
    optionA: "Babel is a Compiler",
    optionB: "Babel is a Transpilar.",
    optionC: "None of the above",
    optionD: "Both A and B are correct",
    asnwer: "optionD",
  },
  {
    prompt: "Which of the following is used to pass data to a component from outside in React.js?",
    optionA: "SetState",
    optionB: "Render with arguments",
    optionC: "Props",
    optionD: "PropTypes",
    asnwer: "optionC",
  },
  {
    prompt: "Which of the following function is used to change the state of the React.js component?",
    optionA: "this.setState",
    optionB: "this.setChangeState",
    optionC: "this.State{}",
    optionD: "None of the above.",
    asnwer: "optionA",
  },
  {
    prompt: "In which language is React.js written?",
    optionA: "PHP",
    optionB: "JavaScript",
    optionC: "Java",
    optionD: "Python",
    asnwer: "optionB",
  },
];
